[shell]
program = "/usr/local/bin/tmux"
args = ["new-session",  "-A", "-s",  "main"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
size = 16

[window]
opacity = 0.8
blur = true
title = "Terminal"
decorations = "Buttonless"

