[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
size = 22

[window]
opacity = 0.8
blur = true
title = "Terminal"
decorations = "Buttonless"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
